name: Deploy to Azure App Service

on:
  push:
    branches:
      - main  # Change this to your deployment branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    
    # Checkout the repo
    - name: Checkout code
      uses: actions/checkout@v3

    # Setup JDK
    - name: Setup Java 21
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'  
        java-version: '21'       

    # Build the JAR inside 'azurecurd' folder
    - name: Build JAR
      run: |
        cd azurecrud
        mvn clean package -DskipTests  

    # Deploy JAR using Azure Publish Profile
    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: "YOUR_AZURE_APP_SERVICE_NAME"  # Replace with your App Service name
        publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
        package: "azurecurd/target/*.jar"
